//
// Created by Paul VANHAESEBROUCK on 25/11/2015.
//

#ifndef GRAPHCUT_TEXTURES_RANDOMOFFSETCHOOSER_H
#define GRAPHCUT_TEXTURES_RANDOMOFFSETCHOOSER_H


class RandomOffsetChooser {

};


#endif //GRAPHCUT_TEXTURES_RANDOMOFFSETCHOOSER_H
